"""del_title

Revision ID: 8ad2e49a9c28
Revises: 899333aa0abf
Create Date: 2020-06-07 18:14:39.231396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ad2e49a9c28'
down_revision = '899333aa0abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('title', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
