"""add fullName

Revision ID: 3db586e9892a
Revises: 1b8eef85bad7
Create Date: 2020-06-07 18:25:17.751609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db586e9892a'
down_revision = '1b8eef85bad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullName', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fullName')
    # ### end Alembic commands ###
